container:
  - components/docker/**/Dockerfile
  - rootfs/**

docs:
  - docs/**
  - README.md

automation:
  - .github/**
  - .spacelift/**
  - Makefile
  - .pre-commit-config.yaml

configuration:
  - stacks/**


