name: 👽 Atmos Terraform Plan
run-name: plan ${{ inputs.component }}/${{ inputs.stack }}/${{ inputs.atmos_pro_run_id}}
on:
  workflow_dispatch:
    inputs:
      component:
        description: "Atmos Component"
        type: string
      stack:
        description: "Atmos Stack"
        type: string
      sha:
        description: "Commit SHA"
        type: string
      atmos_pro_run_id:
        description: "Atmos Pro Run ID"
        type: string

concurrency:
  group: "${{ inputs.component }}-${{ inputs.stack }}"
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    name: Plan ${{ inputs.stack }} ${{ inputs.component }}
    runs-on:
      - "ubuntu-latest"
    steps:
      - name: Plan Atmos Component
        uses: cloudposse/github-action-atmos-terraform-plan@feature/DEV-2465-support-stack-locking
        with:
          component: ${{ inputs.component }}
          stack: ${{ inputs.stack }}
          sha: ${{ inputs.sha }}
          atmos-version: ${{ vars.ATMOS_VERSION }}
          atmos-config-path: ${{ vars.ATMOS_CONFIG_PATH }}
